nome = input('Digite o seu nome completo: ')
print('Nome completo: {}'.format(nome))
print('Nome com todas as letras maiusculas: {}'.format(nome.upper()))
print('Nome com todas as letras minusculas: {}'.format(nome.lower()))
total = len(nome) - nome.count(' ')
print('Total de caracteres, sem os espaços: {}'.format(total))
div = nome.split()
tot1 = len(div[0])
print('Total de caracteres do primeiro nome: {}'.format(tot1))